# Generated by Django 3.1.4 on 2020-12-04 15:58

import discordlogin.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', discordlogin.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.AddField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
