# Generated by Django 3.1.4 on 2020-12-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0002_auto_20201204_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
